name: CI Pipeline for Spring Boot

on:
  push:
    branches-ignore:
      - staging
      - production
      - development

  pull_request:
    branches:
      - development
      - staging
      - production

jobs:

  unit-tests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: integration
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run unit tests
        run: ./mvnw test -Punit-tests



  integration-tests:
    name: 🔗 Integration Tests
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: integration
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start Docker
        run: sudo service docker start

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run integration tests
        run: ./mvnw test -Pintegration-tests



  e2e-tests:
    name: 🚀 E2E Tests
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: integration
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION }}

    if: github.event_name == 'pull_request' &&
      ((github.base_ref == 'staging' && github.head_ref == 'development') ||
      (github.base_ref == 'production' && github.head_ref == 'staging'))

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run e2e tests
        run: ./mvnw test -Pe2e-tests
